import React, { useState, useRef } from "react"
import Head from 'next/head'
import Image from 'next/image'
import styles from '../styles/Home.module.css'
import { motion, useViewportScroll, useTransform } from 'framer-motion'
import { useInView } from "react-intersection-observer"
import Link from 'next/link'
import KeyboardCommandKeyIcon from '@mui/icons-material/KeyboardCommandKey';
import events from "../utils/events"
import Card from "../components/Card"
import Profile from "../components/Profile"
import eventHeads from "../utils/profile"
import Tilt from "react-parallax-tilt"
import { teamHead } from "../utils/framer"
import { useRouter } from "next/router"
import { isMobile } from "react-device-detect"
// import "slick-carousel/slick/slick.css";
// import "slick-carousel/slick/slick-theme.css";
import Slider from "react-slick"

export default function Home() {

  const { scrollY, scrollYProgress } = useViewportScroll()
  const { ref: aboutContainer, inView } = useInView({ threshold: 0.2 });
  const cursorRef = useRef(null)
  const titleSponsorRef = useRef(null)
  const router = useRouter()
  const settings = {
    dots: true,
    infinite: true,
    arrow: false,
    speed: 500,
    slidesToShow: 1,
    slidesToScroll: 1,
    autoplay: true,
    autoplaySpeed: 3000,
  };


  const transform1 = useTransform(scrollY, [2200, 3000], [0.2, 1]);
  const transform2 = useTransform(scrollY, [1800, 2200], [0.2, 1]);
  const transform3 = useTransform(scrollY, [1400, 1800], [0.2, 1]);
  const transform4 = useTransform(scrollY, [1000, 1400], [0.2, 1]);

  const setMark = () => {

  }
  return (
    <div>
      <Head>
        <title>Technunctus</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/static/logo.png" />
      </Head>

      <div className="grid sm:grid-cols-[0.6fr,0.25fr] relative items-center coverBg"
        style={{ height: "calc(100vh - 92px)" }}
      >
        <Image src="/static/page.png"
          alt="logo headers"
          layout="fill"
          objectFit="cover"
          objectPosition={"bottom"}
          className="-z-10"
        />
        <div className="sm:p-20 text-center sm:text-left z-40">
          <motion.p className="text-xl sm:text-3xl text-white"> IIT Jammu presents</motion.p>

          <motion.p className="text-5xl sm:text-[8vw]  font-bold hTitle"> Technunctus</motion.p>
          <motion.p className="text-xl sm:text-3xl text-white">2023</motion.p>

          <Link href="/e">
            <a className="gradientButton mt-4 cursor-pointer inline-block">
              Check Events
            </a>
          </Link>
          {/* <Link href="/buy_pass">
            <a className="gradientButton mt-4 cursor-pointer inline-block ml-5">
              Buy Pass
            </a>
          </Link> */}
        </div>
        <div className='hidden sm:block relative'>
          <Image
            src="/static/logo.png"
            alt="Technunctus Logo"
            layout='fixed'
            height={"400"}
            width={"400"}
            objectFit='contain'
          />
        </div>
      </div>


      <motion.div
        // initial="initial"
        // exit="exit"
        // animate={inView && "animate"}
        // variants={teamHead}
        // style={{ height: isMobile ? "auto" : "80vh" }}

        ref={aboutContainer} className="sm:h-[80vh] mb-12 sm:mb-0 grid place-items-center">
        <div className="bg-black mx-8 sm:mx-20 rounded ">
          <div className='grid sm:grid-cols-[0.3fr,0.7fr] justify-center  items-center'>
            <div className="h-80 sm:h-full relative gradientRightBorder">
              <Image
                src="https://images.unsplash.com/photo-1637166185518-058f5896a2e9?ixlib=rb-1.2.1&ixid=MnwxMjA3fDB8MHxzZWFyY2h8MTZ8fGZ1dHVyaXN0aWN8ZW58MHx8MHx8&auto=format&fit=crop&w=700&q=60"
                alt="About Team "
                layout="fill"
                objectFit="cover"
              />
            </div>
            <div className="p-4 sm:p-12">
              <p className='text-xl italic'>Theme</p>

              <p className='text-3xl mb-8'>Flamboyant Futuranium</p>
              <p className='text-sm sm:text'>Traversing through the cosmic millennium, we stumble across a distant planet exuding a glitzy vibe. Its tantalizing aura beckons you to surrender yourself to its enticement. Before you lies a symphony of the celestials; Multitudes of watchful eyes throughout the years behold before themselves alongside, the essence of light and color thronging through the air; The brilliance around tempts you to come closer, to drench yourself in its warm embrace.Being drawn towards its ethos is nigh inevitable. So come ushering into this lavish ambience of flamboyance & synergy and immerse yourself within the realms of the future to experience technology like never before.</p>
            </div>
          </div>
        </div>
      </motion.div>


      <div className="my-20 hidden sm:block"
      >
        <p className='text-3xl my-8 text-center'>Event Schedule</p>

        <div className="mx-20 rounded">
          <Slider {...settings}>

            <div>
            <p className="text-4xl font-semibold mb-4">Day 1 (6<sup>th</sup> May) </p>
              <div className="boxsRow" style={{ display: "grid !important", gridTemplateColumns: "repeat(4,1fr)" }}>
                <div className="boxEvent grid place-items-center text-center">INAUGRATION from 6:30 to 8pm & CAD Star from 7pm</div>
                <div className="boxEvent grid place-items-center">UAV 4 U</div>
                <div className="boxEvent grid place-items-center">Amnesia</div>
                <div className="boxEvent grid place-items-center">Star Gazers  </div>
              </div>
            </div>
            <div>
              <p className="text-4xl font-semibold mb-4">Day 2 (7<sup>th</sup> May) </p>

              <div className="boxsRow" style={{ display: "grid", gridTemplateColumns: "repeat(8,1fr) " }}>
                <div className="boxEvent grid place-items-center">Simulate-e-Abaqus(3hr)</div>
                <div className="boxEvent grid place-items-center">Astronomically Smart</div>
                <div className="boxEvent grid place-items-center">Capture the Flag</div>
                <div className="boxEvent grid place-items-center">Fundamentals of Stock Market</div>
                <div className="boxEvent grid place-items-center">TPC</div>
                <div className="boxEvent grid place-items-center">Akhilesh Guest Talk</div>
                <div className="boxEvent grid place-items-center">MESH GUEST TALK(1hr)</div>
                <div className="boxEvent grid place-items-center"
                  style={{ background: "url(https://static.toiimg.com/photo/msid-71050124/71050124.jpg)", backgroundSize: "cover", backgroundPosition: "center" }}
                >The Landers</div>
              </div>
            </div>
            <div>
            <p className="text-4xl font-semibold mb-4">Day 3 (8<sup>th</sup> May) </p>

              <div className="boxsRow" style={{ display: "grid", gridTemplateColumns: "repeat(6,1fr)" }}>
                <div className="boxEvent grid place-items-center"
                  style={{ background: "url(https://images.unsplash.com/photo-1585166059782-f28143545183?ixlib=rb-1.2.1&ixid=MnwxMjA3fDB8MHxzZWFyY2h8M3x8bWVjaGFuaWNhbHxlbnwwfHwwfHw%3D&auto=format&fit=crop&w=700&q=60)" }}
                >Simulate-e-Abaqus(3hr)</div>
                <div className="boxEvent grid place-items-center"
                  style={{ background: "url(https://media.wired.com/photos/5aac56eb491c2d69af42197d/master/pass/Hackathons-RTS12CJ0.jpgg)" }}
                >Hack the Build</div>
                <div className="boxEvent grid place-items-center"
                  style={{ background: "url(https://images.unsplash.com/photo-1581092335397-9583eb92d232?ixlib=rb-1.2.1&ixid=MnwxMjA3fDB8MHxzZWFyY2h8MTJ8fG1lY2hhbmljYWx8ZW58MHx8MHx8&auto=format&fit=crop&w=700&q=60)" }}
                >Tr-SAE-ure</div>
                <div className="boxEvent grid place-items-center"
                  style={{ background: "url(https://images.unsplash.com/photo-1518589794402-58a93db13b83?ixlib=rb-1.2.1&ixid=MnwxMjA3fDB8MHxzZWFyY2h8MTJ8fGFzdHJvbm9teXxlbnwwfHwwfHw%3D&auto=format&fit=crop&w=700&q=60)" }}
                >Astrophysics</div>
                <div className="boxEvent grid place-items-center"
                >NextGen Blockchain</div>
                <div className="font-bold text-4xl boxEvent grid place-items-center"
                  style={{ background: "url(https://media.istockphoto.com/photos/concert-party-picture-id1001487418?b=1&k=20&m=1001487418&s=170667a&w=0&h=933qzZkFeROBf5HU1RVi0oklm6wyDtXwok4-tTrxyLU=)" }}
                >BDM Night</div>
              </div>

            </div>
          </Slider>
        </div>
      </div>

      {/* <div ref={titleSponsorRef} onMouseMove={(e)=>{exactLocation(e)}} className="pt-20 sm:pt-40 overflow-hidden pb-20 grid place-items-center relative">
        <div ref={cursorRef} className="cursor"></div>
        <div className="text-center text-2xl sm:text-3xl">
          <p>Title Sponsors</p>
          <div>
            <Link
              href="/titlesponsorswebsite"
            >
              <a className='flex justify-center text-6xl sm:text-7xl m-4'>
                  <KeyboardCommandKeyIcon className="text-[#39ff14]" style={{fontSize:"5rem"}}/>
                  <p className="ml-4 font-semibold">Android</p>
              </a>
            </Link>
            <p>Marsh McLennan Global Services India Pvt Ltd</p>
          </div>
        </div>
      </div> */}


      <div className="sm:min-h-screen grid place-items-center">
        <div>
          <p className='text-3xl my-8 text-center'>Events</p>
          <div className='grid sm:grid-cols-4 gap-8 mx-8 sm:mx-20'>
            {events.slice(0, 4).map((item, index) => {
              return (
                <Card key={index} {...item} />
              )
            })}
          </div>
          <Link href="/e">
            <a className="hover:text-underline text-center block my-4">Click Here to load more</a>
          </Link>
        </div>
      </div>


      <motion.div
        initial="initial"
        exit="exit"
        animate={inView && "animate"}
        variants={teamHead}
        ref={aboutContainer} className="mt-40 mb-12 sm:mb-0 grid place-items-center">
        <div className="bg-black mx-8 sm:mx-20 rounded ">
          <div className='grid sm:grid-cols-[0.3fr,0.7fr] justify-center  items-center'>
            <div className="h-80 sm:h-full relative gradientRightBorder">
              <Image
                src="https://images.unsplash.com/photo-1518709911915-712d5fd04677?ixlib=rb-1.2.1&ixid=MnwxMjA3fDB8MHxzZWFyY2h8MTJ8fGVuZXJneXxlbnwwfHwwfHw%3D&auto=format&fit=crop&w=700&q=60"
                alt="About Team "
                layout="fill"
                objectFit="cover"
              />
            </div>
            <div className="p-4 sm:p-12">
              <p className='text-3xl mb-8'>Word From Team</p>
              <p className='text-sm sm:text'>Technunctus’23 is a platform for students to manifest their talents by working on challenging problems and to learn and grow from the various talks given by industry experts on contemporary topics and issues. It boasts having more than two dozen events from a multitude of fields like robotics, astronomy, finance, programming and so forth spread across 3 days of engagement, excitement and illumination. It is a pan-India event with participants from all IITs and NITs as well as reputed colleges from Jammu and Kashmir.</p>
              <Link
                href="/a"
              >
                <a className="gradientButton inline-block mt-4">Read More</a>
              </Link>
            </div>
          </div>
        </div>
      </motion.div>

      <motion.div className="sm:h-screen grid place-items-center">
        <div>
          <p className='text-3xl my-8 mr-8 text-center'>Team Members</p>
          <div className='grid sm:grid-cols-3 gap-8 mx-8 sm:mx-20'>
            {eventHeads.slice(0, 5).map((item, index) => {
              return (
                <Tilt key={item.key}>
                  <Profile {...item} />
                </Tilt>
              )
            })}
            <Link
              href="/t"
              passHref={true}
            >
              <motion.a
                whileTap={{ scale: 0.95 }}
                className='m-1 grid place-items-center border border-[#00ffff] rounded'>
                <p>See More...</p>
              </motion.a>
            </Link>
          </div>
        </div>
      </motion.div>



    </div>
  )
}
